basePath: /
definitions:
  handler.ErrorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
  handler.LoginRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  handler.RegisterRequest:
    properties:
      email:
        example: user@example.com
        type: string
      password:
        example: password123
        type: string
    type: object
  handler.TokenResponse:
    properties:
      token:
        example: jwt_token_placeholder
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: API для пет проекта.
  title: Threads Clone API
  version: "1.0"
paths:
  /auth/{provider}:
    get:
      description: Redirects the user to the chosen OAuth provider's authentication
        page.
      parameters:
      - description: OAuth provider
        enum:
        - google
        - vk
        - telegram
        in: path
        name: provider
        required: true
        type: string
      responses:
        "302":
          description: Redirect URL
          schema:
            type: string
        "400":
          description: Error message
          schema:
            additionalProperties:
              type: string
            type: object
      summary: OAuth Redirect
      tags:
      - Auth
  /auth/{provider}/callback:
    get:
      description: Handles the OAuth callback from the specified provider.
      parameters:
      - description: OAuth provider
        enum:
        - google
        - vk
        - telegram
        in: path
        name: provider
        required: true
        type: string
      - description: Authorization code (used for Google and VK)
        in: query
        name: code
        type: string
      - description: Telegram user id (for Telegram)
        in: query
        name: id
        type: string
      - description: Telegram auth date (for Telegram)
        in: query
        name: auth_date
        type: string
      - description: Telegram hash (for Telegram)
        in: query
        name: hash
        type: string
      - description: Telegram first name (optional)
        in: query
        name: first_name
        type: string
      - description: Telegram last name (optional)
        in: query
        name: last_name
        type: string
      - description: Telegram username (optional)
        in: query
        name: username
        type: string
      - description: Telegram photo URL (optional)
        in: query
        name: photo_url
        type: string
      responses:
        "200":
          description: TokenResponse
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Error message
          schema:
            additionalProperties:
              type: string
            type: object
      summary: OAuth Callback
      tags:
      - Auth
  /login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token response
          schema:
            $ref: '#/definitions/handler.TokenResponse'
        "400":
          description: Invalid credentials or request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Login user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user with email and password
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handler.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: JWT token response
          schema:
            $ref: '#/definitions/handler.TokenResponse'
        "400":
          description: Invalid request or error during registration
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Register a new user
      tags:
      - Auth
swagger: "2.0"
